version: '3.8'

services:
  db:
    image: mariadb:12.1-ubi
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD_FILE: /run/secrets/mysql_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network
    command: '--default-authentication-plugin=mysql_native_password'
    secrets:
      - mysql_root_password
      - mysql_password
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  wordpress:
    image: wordpress:6.9.0-php8.5-apache
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_network
    secrets:
      - mysql_password
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

volumes:
  db_data:
  wordpress_data:

networks:
  wordpress_network:
    driver: overlay

secrets:
  mysql_root_password:
    external: true
  mysql_password:
    external: true
